version: '3.9'

services:
  restfull-rabbitmq:
    image: rabbitmq:4-management
    container_name: restfull-rabbitmq
    ports:
      - '5672:5672'      # AMQP
      - '15672:15672'    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - backend

  restfull-mongodb:
    image: mongo:8
    container_name: restfull-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
